### ISSUE TITLE
Création de la base de donnée

### ISSUE THREAD

**Issue by joshua-vegas** [lpdw/faclabprojet0#3]
Mise en place du MCD / MPD / MLD avec Analysesi
Création du fichier Sql
Création des différentes pages avec Scaffold

**Comment by Pierrecl** [comment]
Could we close this issue ?

![mcdfaclab](https://cloud.githubusercontent.com/assets/16536715/18952967/6dd45a12-864c-11e6-8049-bc20811baff2.png)

![mpdfaclab](https://cloud.githubusercontent.com/assets/16536715/18952939/5399d0b4-864c-11e6-9814-21da8beae36c.png)

`rails generate scaffold Visits date_visit:timestamp place_id:integer`

--------- FK is generated only in rails -------------

`rails generate scaffold Places name:string`

**Comment by joshua-vegas** [comment]
If everything is working, sure.
